export const releases = [
  {
    id: '001',
    title: 'Variegated EP',
    image: 'images/releases/variegated-ep.jpg',
    comment: 'IDM/Techno',
    label: 'on sunday recordings',
    url: 'https://on-sunday-recordings.bandcamp.com/album/variegated-ep',
  },
  {
    id: '002',
    title: '4location EP',
    image: 'images/releases/4location-ep.jpg',
    comment: 'IDM/Techno',
    label: 'on sunday recordings',
    url: 'https://on-sunday-recordings.bandcamp.com/album/4location-ep',
  },
  {
    id: '003',
    title: 'moment',
    image: 'images/releases/moment.jpg',
    comment: 'IDM/Techno',
    label: 'on sunday recordings',
    url: 'https://on-sunday-recordings.bandcamp.com/album/moment',
  },
  {
    id: '004',
    title: 'newexoskeleton',
    image: 'images/releases/newexoskeleton.jpg',
    comment: 'IDM/Techno',
    label: 'on sunday recordings',
    url: 'https://on-sunday-recordings.bandcamp.com/album/newexoskeleton',
  },
  {
    id: '005',
    title: 'CCCCCC',
    image: 'images/releases/cccccc.jpg',
    comment: 'IDM/EDM',
    label: 'ceramicrecords',
    url: 'https://ceramicrecords.net/release/crm_039/',
  },
  {
    id: '006',
    title: 'CDFTG2',
    image: 'images/releases/CDFTG2.jpg',
    comment: 'IDM/EDM',
    label: 'ceramicrecords',
    url: 'https://ceramicrecords.net/release/crm_053/',
  },
  {
    id: '007',
    title: 'My Low Xeats',
    image: 'images/releases/my-low-xeats.jpg',
    comment: 'Lo-Fi HipHop',
    label: 'Easy + Nice',
    url: 'https://easyandnice.bandcamp.com/album/my-low-xeats',
  },
];
